### ISSUE TITLE
Request for file removal: Arnold_v0.1-Regular.otf

### ISSUE THREAD

**Issue by PhilippNeumeyer** [uonai/Uonai#1]
When using http://www.getthefont.com/, I found your font file [Arnold_v0.1-Regular.otf](http://github.com/uonai/Uonai/blob/4149797f27e06ca918197009f913762950e8a0af/public/fonts/Arnold_v0.1-Regular.otf), uploaded in this repository. I believe that this file was uploaded here by mistake, because its license does not allow distribution through a public website.

I would like to kindly ask you to remove this font file from the repository.

Kind regards,

**Comment by uonai** [comment]
Hi @PhilippNeumeyer , thanks for bringing this to my attention. I have removed from repository on this commit: https://github.com/uonai/Uonai/commit/23cd0f08551eb3262fc93ef38937b91dc036e303
